{% set normalized_page_name = page.name | lower %}
{% set is_about_page = page.name == 'Quiénes Somos' or page.name == 'Quienes Somos' %}
{% set is_how_to_buy_page = page.name == 'Cómo Comprar' or page.name == 'Como Comprar' %}
{% set is_faq_page = page.name == 'Preguntas Frecuentes' %}
{% set is_size_guide_page = 'talle' in normalized_page_name or 'size' in normalized_page_name %}
{% set is_returns_page = 'devolucion' in normalized_page_name or 'devolución' in normalized_page_name %}

{% if is_about_page %}
<section class="ivana-page-shell ivana-institutional-page ivana-about-page"><div class="container py-4 py-md-5"><div class="ivana-about-layout"><header class="ivana-about-heading"><span class="ivana-about-kicker">Nuestra historia</span><h1>Quiénes Somos</h1><span class="ivana-title-line"></span><p>Ivana Design es una marca de prendas deportivas y bikinis premium confeccionadas con telas importadas de Brasil.</p><p>Nos enfocamos en crear diseños que se adapten a vos y te hagan sentir cómoda, segura y libre en cada movimiento.</p></header><div class="ivana-about-centered-image"><div class="user-content ivana-about-real-content">{{ page.content }}</div></div><div class="ivana-institutional-cta"><p>¿Lista para encontrar tu próxima prenda favorita?</p><a href="/coleccion/">Ver colección</a></div></div></div></section>
{% elseif is_how_to_buy_page %}
<section class="ivana-page-shell ivana-institutional-page ivana-how-page"><div class="container py-4 py-md-5"><div class="ivana-about-layout"><header class="ivana-about-heading"><span class="ivana-about-kicker">Cómo Comprar</span><h1>Así es tu experiencia de compra en Ivana Design</h1><span class="ivana-title-line"></span><p>Queremos que tu experiencia sea simple, segura y satisfactoria de principio a fin.</p></header><section class="ivana-how-steps" aria-label="Pasos para comprar"><article><span class="ivana-how-icon">▢</span><h3>1. Elegí tus productos</h3><p>Explorá nuestra colección y elegí las prendas que más te gusten.</p></article><article><span class="ivana-how-icon">▭</span><h3>2. Realizá tu compra</h3><p>Seleccioná el método de pago que prefieras y completá tus datos.</p></article><article><span class="ivana-how-icon">▱</span><h3>3. Preparamos tu pedido</h3><p>Preparamos tu pedido con cuidado y lo despachamos.</p></article><article><span class="ivana-how-icon">◇</span><h3>4. Recibí tu pedido</h3><p>Recibí tu pedido en la puerta de tu casa.</p></article></section><div class="ivana-institutional-cta"><p>¿Lista para elegir tu próxima prenda favorita?</p><a href="/coleccion/">Ver colección</a></div></div></div></section>
{% elseif is_faq_page %}
<section class="ivana-page-shell ivana-institutional-page ivana-faq-page"><div class="container py-4 py-md-5"><div class="ivana-about-layout"><header class="ivana-about-heading"><span class="ivana-about-kicker">Preguntas Frecuentes</span><h1>Resolvemos las consultas más habituales</h1><span class="ivana-title-line"></span><p>Encontrá respuestas a las preguntas que más nos hacen.</p></header><section class="ivana-faq-list" aria-label="Preguntas frecuentes"><details><summary>¿Cuáles son los medios de pago?</summary><p>Podés abonar con los medios de pago disponibles al finalizar tu compra.</p></details><details><summary>¿Cuánto tarda el envío?</summary><p>Los tiempos de entrega dependen de tu ubicación y del operador logístico.</p></details><details><summary>¿Realizan cambios?</summary><p>Sí. Los cambios se gestionan dentro del plazo informado por la tienda.</p></details><details><summary>¿Cómo sé mi talle?</summary><p>Revisá la guía de talles o escribinos para ayudarte.</p></details><details><summary>¿Qué sucede si el producto no me queda?</summary><p>Podés consultar las opciones de cambio disponibles con nuestro equipo.</p></details><details><summary>¿Hacen envíos a todo el país?</summary><p>Sí. Realizamos envíos a todo el país.</p></details></section><section class="ivana-faq-contact"><h2>¿No encontraste tu respuesta?</h2><p>Estamos para ayudarte.</p><div><a href="/contacto/">Contacto</a><a href="/coleccion/">Ir a colección</a></div></section></div></div></section>
{% elseif is_returns_page %}
<section class="ivana-page-shell ivana-institutional-page ivana-return-page"><main class="rp-wrap"><header class="rp-hero"><div class="rp-hero-icon">↩</div><div><h1>Política de Devolución</h1><span class="rp-line"></span><p>Cambios y devoluciones simples para que compres con tranquilidad.</p></div></header><section class="rp-card-grid" aria-label="Condiciones principales"><article class="rp-card"><span class="rp-icon">□</span><h3>30 días</h3><p>Tenés 30 días corridos desde la fecha de compra para solicitar el cambio o devolución.</p></article><article class="rp-card"><span class="rp-icon">◇</span><h3>Estado del producto</h3><p>El producto debe estar sin uso, con sus etiquetas y en el embalaje original.</p></article><article class="rp-card"><span class="rp-icon">☰</span><h3>Comprobante</h3><p>Es fundamental conservar el ticket o comprobante de compra.</p></article></section><h2>¿Cómo solicitarlo?</h2><section class="rp-wide"><article class="rp-method"><span class="rp-icon">⌂</span><div><h3>En tienda física</h3><p>Acercate a nuestra sucursal con tu ticket de compra. Nuestro equipo te ayudará a gestionar el cambio.</p></div></article><span class="rp-divider"></span><article class="rp-method"><span class="rp-icon">☏</span><div><h3>Por WhatsApp</h3><p>Escribinos al +54 11 2476 9969 detallando tu solicitud. Coordinamos el retiro o envío del producto.</p></div></article></section><h2>¿Qué sucede después?</h2><section class="rp-steps"><article class="rp-step"><span class="rp-num">1</span><h3>Recibimos tu solicitud</h3><p>Nos contactás por la opción que prefieras.</p></article><span class="rp-arrow">›</span><article class="rp-step"><span class="rp-num">2</span><h3>Verificamos el producto</h3><p>Revisamos que cumpla con las condiciones de nuestra política.</p></article><span class="rp-arrow">›</span><article class="rp-step"><span class="rp-num">3</span><h3>Gestionamos la solución</h3><p>Realizamos el cambio o procesamos la devolución del dinero.</p></article></section><section class="rp-guarantee"><div><h3>Nuestra garantía</h3><p>Queremos que tu experiencia sea siempre positiva. Estamos para ayudarte y encontrar la mejor solución.</p></div><span class="rp-divider"></span><ul class="rp-checks"><li>Brindarte tranquilidad y confianza al comprar.</li><li>Facilitarte el proceso para que no pierdas tiempo.</li><li>Garantizar tu satisfacción para que vuelvas a elegirnos.</li></ul></section><section class="rp-cta"><h2>¿Tenés dudas?</h2><p>Estamos para ayudarte. Contactanos y te asesoramos.</p><div class="rp-actions"><a href="https://wa.me/5491124769969">Contactar por WhatsApp</a><a href="/coleccion/">Ver colección</a></div></section></main></section>
{% elseif is_size_guide_page %}
<section class="ivana-page-shell ivana-institutional-page ivana-size-original"><header class="sg-hero"><span class="sg-kicker">Guía de Talles</span><h1>Encontrá el talle ideal para vos</h1><span class="sg-line"></span><p>Las medidas corresponden al cuerpo, no a la prenda. Usá esta guía como referencia para elegir tu talle.</p></header><main class="sg-wrap"><section class="sg-card"><div class="sg-content user-content">{{ page.content }}</div><div class="sg-note"><strong>Consejo de calce</strong><p>Si estás entre dos talles, elegí el talle más grande.</p></div><div class="sg-actions"><a href="/contacto/">Consultar talle</a><a href="/coleccion/">Ver colección</a></div></section></main></section>
{% else %}
<section class="ivana-page-shell"><div class="container py-4 py-md-5">{% embed "snipplets/page-header.tpl" with {page_header_class: 'ivana-page-hero', page_header_title_class: 'ivana-page-title'} %}{% block page_header_text %}{{ page.name }}{% endblock page_header_text %}{% endembed %}<div class="user-content ivana-rich-content pb-5">{{ page.content }}</div></div></section>
{% endif %}